from __future__ import annotations

from typing import Any, Protocol


class ILogger(Protocol):
    """Structured logging contract decoupled from stdlib `logging`."""

    def debug(self, msg: str, **kwargs: Any) -> None: ...
    def info(self, msg: str, **kwargs: Any) -> None: ...
    def warning(self, msg: str, **kwargs: Any) -> None: ...
    def error(self, msg: str, **kwargs: Any) -> None: ...
    def exception(self, msg: str, **kwargs: Any) -> None: ...
